services:
  php-fpm: &default
    image: aiq_gdakuzak:latest
    build:
      context: .
      target: base
    # user: "1000:1000"
    working_dir: /application
    volumes:
      - .:/application
  nginx:
    image: nginx:alpine
    volumes:
      - .:/application
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80
    depends_on:
      - php-fpm
      - postgres
  postgres:
    image: postgres:16.0-alpine3.18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aiq
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

volumes:
  postgres: {}